### ISSUE TITLE
Team Codes documentation required

### ISSUE THREAD

**Issue by MaheshBharadwaj** [MaheshBharadwaj/Paneka-discord-bot#2]
Team codes need to be added to README as a table like it exists for the `League Codes`  under a section titled **Team Codes**
The team codes are  [here](https://github.com/MaheshBharadwaj/paneka/blob/master/source/teamcodes.json)

**Extra:** The teams may be grouped by leagues

**Comment by Maddoxx88** [comment]
Hey, can I contribute to this issue? @MaheshBharadwaj

**Comment by MaheshBharadwaj** [comment]
Sure :+1:

**Comment by MaheshBharadwaj** [comment]
> Hey, can I contribute to this issue? @MaheshBharadwaj

Sure :+1:

**Comment by MaheshBharadwaj** [comment]
Fixed in  #3
